name: Scheduled Python Script

on:
  schedule:
    - cron: '00 06 1-31 * *' # Schedule to run every minute

jobs:
  build:
    runs-on: ubuntu-latest
    
#     strategy:
#       matrix:
#         node-version: [10.x, 12.x, 14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
    
        
    - name: setup python
      uses: actions/setup-python@v3
      with:
        python-version: '3.11' # Replace 'x' with the desired Python version

    - name: install python packages
      run: |
        python -m pip install --upgrade pip pandas
        pip install -r requirements.txt

    - name: commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git diff-index --quiet HEAD || (git commit -a -m "updated logs" --allow-empty)

    - name: push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main 

    - name: Run Python script
      run: |
        python main.py
    
    - name: Run Python birthday script
      run: |
        python birthday-wisher/main-birthday.py
