name: Scheduled Python Script

on:
  schedule:
    - cron: '* * * 06 *' # Schedule to run every minute

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11 # Replace 'x' with the desired Python version

      - name: Run Python script
        run: |
          python3 main.py
